export { PolygonIcon } from "./polygon-icon";
export { StarIcon } from "./star-icon";
export { MenuMobileIcon } from "./menu-icon";
export { Linkedin } from "./linkedin";
export { TwitterIcon } from "./twitter";
export { Facebook } from "./facebook"
export { GithubIcon } from "./github";
export { InstagramIcon } from "./instagram";
export { LinkedInIcon } from "./linked-in";
export { CloseIcon } from "./close-icon";
export { ClockIcon } from "./clock-icon";
export { PinkCircle } from "./pink-circle";
export { ErrorImage } from "./404-image";
export { XlFooter } from "./xl-footer";
export { ArrowIcon } from "./arrow-icon";
