export { PolygonIcon } from "./polygon-icon";
export { StarIcon } from "./star-icon";
export { MenuMobileIcon } from "./menu-icon";
export { Linkedin } from "./linkedin";
export { TwitterIcon } from "./twitter";
export { Facebook } from "./facebook"
export { GithubIcon } from "./github";
export { InstagramIcon } from "./instagram";
export { CloseIcon } from "./close-icon";
export { LinkedInIcon } from "./linked-in";
